import { IMAGES } from "@/assets";

export const sampleProducts = [
    {
      id: 15,
      image: IMAGES.GotInspiration.src,
      category: "Sofa",
      title: "Modern 3-Seater",
      rating: 4.8,
      price: "30,000",
    },
    {
      id: 25,
      image: IMAGES.GotInspiration,
      category: "Chair",
      title: "Luxury Armchair",
      rating: 4.5,
      price: "12,000",
    },
    {
      id: 19,
      image: IMAGES.GotInspiration,
      category: "Sofa",
      title: "Modern 3-Seater",
      rating: 4.8,
      price: "30,000",
    },
    {
      id: 22,
      image: IMAGES.GotInspiration,
      category: "Chair",
      title: "Luxury Armchair",
      rating: 4.5,
      price: "12,000",
    },
    {
      id: 16,
      image: IMAGES.GotInspiration,
      category: "Sofa",
      title: "Modern 3-Seater",
      rating: 4.8,
      price: "30,000",
    },
    {
      id: 75,
      image: IMAGES.GotInspiration,
      category: "Chair",
      title: "Luxury Armchair",
      rating: 4.5,
      price: "12,000",
    },
    {
      id: 1,
      image: IMAGES.GotInspiration,
      category: "Sofa",
      title: "Modern 3-Seater",
      rating: 4.8,
      price: "30,000",
    },
    {
      id: 20,
      image: IMAGES.GotInspiration,
      category: "Chair",
      title: "Luxury Armchair",
      rating: 4.5,
      price: "12,000",
    },
    {
      id: 81,
      image: IMAGES.GotInspiration,
      category: "Sofa",
      title: "Modern 3-Seater",
      rating: 4.8,
      price: "30,000",
    },
    {
      id: 72,
      image: IMAGES.GotInspiration,
      category: "Chair",
      title: "Luxury Armchair",
      rating: 4.5,
      price: "12,000",
    },
    {
      id: 31,
      image: IMAGES.GotInspiration,
      category: "Sofa",
      title: "Modern 3-Seater",
      rating: 4.8,
      price: "30,000",
    },
    {
      id: 2,
      image: IMAGES.GotInspiration,
      category: "Chair",
      title: "Luxury Armchair",
      rating: 4.5,
      price: "12,000",
    },
    {
      id: 21,
      image: IMAGES.GotInspiration,
      category: "Sofa",
      title: "Modern 3-Seater",
      rating: 4.8,
      price: "30,000",
    },
    {
      id: 42,
      image: IMAGES.GotInspiration,
      category: "Chair",
      title: "Luxury Armchair",
      rating: 4.5,
      price: "12,000",
    },
    {
      id: 14,
      image: IMAGES.GotInspiration,
      category: "Sofa",
      title: "Modern 3-Seater",
      rating: 4.8,
      price: "30,000",
    },
    {
      id: 3,
      image: IMAGES.GotInspiration,
      category: "Chair",
      title: "Luxury Armchair",
      rating: 4.5,
      price: "12,000",
    },
  ];