import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Lokplaaza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
